apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-web
  labels:
    app: trend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trend-web
  template:
    metadata:
      labels:
        app: trend-web
    spec:
      containers:
        - name: trend-app
          image: thra21/guvi-project-repo:trend-web
          ports:
            - containerPort: 3000

